backend:
  name: github
  repo: MisakaMikato0/my-blog
  branch: master
  base_url: https://my-blog-decap-oauth.ltznb666.workers.dev
  auth_endpoint: auth

media_folder: public/assets
public_folder: /assets
publish_mode: editorial_workflow

local_backend: true

collections:
  - name: posts
    label: 文章
    label_singular: 文章
    folder: src/content/posts
    create: true
    delete: true
    nested:
      depth: 2
    format: yaml-frontmatter
    sortable_fields: [published, title]
    summary: "{{title}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: published, widget: datetime, format: YYYY-MM-DD, picker_utc: false }
      - { label: 描述, name: description, widget: text, required: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: category, widget: string }
      - { label: 草稿, name: draft, widget: boolean, default: false, required: false }
      - { label: 封面图, name: image, widget: image, required: false }
      - { label: 正文, name: body, widget: markdown }
